package com.vfernandes.Utils.Validators;

import java.util.regex.Pattern;

public class EVPValidator {
    private static final String EVP_REGEX = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
    private static final Pattern EVP_PATTERN = Pattern.compile(EVP_REGEX);

    /***
     * Checks if the key is an EVP number following the <a href="https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/api-dict.html#tag/Directory">DICT  API</a> rules.
     * Allowed example: 123e4567-e89b-12d3-a456-426655440000
     * An EVP is a key generated by the DICT API
     * @return boolean - True if it's a EVP False if it's not a EVP
     */
    public static boolean isValidEVP(String evp ){
        return EVP_PATTERN.matcher(evp).matches();
    }
}
